openapi: 3.0.0
info:
  title: Dragon Ball API Rest
  version: 1.0.0
  description: www.dragonball-api.com unofficial documentation 
servers:
  - url: https://www.dragonball-api.com/api
tags:
  - name: Characters
  - name: Planets
  - name: Transformations
paths:
  /api/characters:
    get:
      summary: Get all characters if no params are provided, limit to 10 by default
      tags: [Characters]
      parameters:
        - name: Page
          in: query
          description: Page number
          schema: { type: number }
        - name: Limit
          in: query
          description: Number of items per page
          schema: { type: number }
        - name: Name
          in: query
          description: Character name
          schema: { type: string }
        - name: Gender
          in: query
          description: Character gender
          schema: 
            type: string
            enum: [Male, Female, Other, Unknown] 
        - name: Race
          in: query
          description: Character race
          schema: 
            type: string
            enum: [Saiyan, Namekian, Human, Majin, Frieza Race, Jiren Race, Android, God, Angel, Evil, Unknown, Nucleico benigno, Nucleico] 
        - name: Affiliation
          in: query
          description: Character affiliation
          schema: 
            type: string
            enum: [Z Fighter, Red Ribbon Army, Namekian Warrior, Freelancer, Army of Frieza, Other, Pride Troopers, Assistant of Vermoud, Assistant of Beerus, Villain] 
      responses:
        "200":
          description: Character List
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/PaginatedCharacters"
                  - type: array
                    items:
                      $ref: "#/components/schemas/Character"
              examples:
                paginated:
                  summary: Unfiltered (paginated)
                  value:
                    items:
                      - id: 1
                        name: "Goku"
                        ki: "60.000.000"
                        maxKi: "90 Septillion"
                        race: "Saiyan"
                        gender: "Male"
                        description: "El protagonista de la serie, conocido por su gran poder y personalidad amigable. Originalmente enviado a la Tierra como un infante volador con la misión de conquistarla. Sin embargo, el caer por un barranco le proporcionó un brutal golpe que si bien casi lo mata, este alteró su memoria y anuló todos los instintos violentos de su especie, lo que lo hizo crecer con un corazón puro y bondadoso, pero conservando todos los poderes de su raza. No obstante, en la nueva continuidad de Dragon Ball se establece que él fue enviado por sus padres a la Tierra con el objetivo de sobrevivir a toda costa a la destrucción de su planeta por parte de Freeza. Más tarde, Kakarot, ahora conocido como Son Goku, se convertiría en el príncipe consorte del monte Fry-pan y líder de los Guerreros Z, así como el mayor defensor de la Tierra y del Universo 7, logrando mantenerlos a salvo de la destrucción en innumerables ocasiones, a pesar de no considerarse a sí mismo como un héroe o salvador."
                        image: "https://dragonball-api.com/characters/goku_normal.webp"
                        affiliation: "Z Fighter"
                        deletedAt: null
                      - id: 2
                        name: "Vegeta"
                        ki: "54.000.000"
                        maxKi: "19.84 Septillion"
                        race: "Saiyan"
                        gender: "Male"
                        description: "Príncipe de los Saiyans, inicialmente un villano, pero luego se une a los Z Fighters. A pesar de que a inicios de Dragon Ball Z, Vegeta cumple un papel antagónico, poco después decide rebelarse ante el Imperio de Freeza, volviéndose un aliado clave para los Guerreros Z. Con el paso del tiempo llegaría a cambiar su manera de ser, optando por permanecer y vivir en la Tierra para luchar a su lado contra las inminentes adversidades que superar. Junto con Piccolo, él es de los antiguos enemigos de Goku que ha evolucionando al pasar de ser un villano y antihéroe, a finalmente un héroe a lo largo del transcurso de la historia, convirtiéndose así en el deuteragonista de la serie."
                        image: "https://dragonball-api.com/characters/vegeta_normal.webp"
                        affiliation: "Z Fighter"
                        deletedAt: null
                      - id: 3
                        name: "Piccolo"
                        ki: "2.000.000"
                        maxKi: "500.000.000"
                        race: "Namekian"
                        gender: "Male"
                        description: "Es un namekiano que surgió tras ser creado en los últimos momentos de vida de su padre, siendo su actual reencarnación. Aunque en un principio fue el archienemigo de Son Goku, con el paso del tiempo fue haciéndose menos malvado hasta finalmente convertirse en un ser bondadoso y miembro de los Guerreros Z. A través del tiempo, también comenzó a tomarle cariño a su discípulo Son Gohan, a quien veía como una especie de 'vástago' y formando un lazo de amistad con este."
                        image: "https://dragonball-api.com/characters/picolo_normal.webp"
                        affiliation: "Z Fighter"
                        deletedAt: null
                      - id: 4
                        name: "Bulma"
                        ki: "0"
                        maxKi: "0"
                        race: "Human"
                        gender: "Female"
                        description: "Bulma es la protagonista femenina de la serie manga Dragon Ball y sus adaptaciones al anime Dragon Ball, Dragon Ball Z, Dragon Ball Super y Dragon Ball GT. Es hija del Dr. Brief y su esposa Panchy, hermana menor de Tights y una gran amiga de Son Goku con quien inicia la búsqueda de las Esferas del Dragón. En Dragon Ball Z tuvo a Trunks, primogénito de quien sería su esposo Vegeta, a su hija Bra[3] y su hijo adulto del tiempo alterno Trunks del Futuro Alternativo."
                        image: "https://dragonball-api.com/characters/bulma.webp"
                        affiliation: "Z Fighter"
                        deletedAt: null
                      - id: 5
                        name: "Freezer"
                        ki: "530.000"
                        maxKi: "52.71 Septillion"
                        race: "Frieza Race"
                        gender: "Male"
                        description: "Freezer es el tirano espacial y el principal antagonista de la saga de Freezer."
                        image: "https://dragonball-api.com/characters/Freezer.webp"
                        affiliation: "Army of Frieza"
                        deletedAt: null
                      - id: 6
                        name: "Zarbon"
                        ki: "20.000"
                        maxKi: "30.000"
                        race: "Frieza Race"
                        gender: "Male"
                        description: "Zarbon es uno de los secuaces de Freezer y un luchador poderoso."
                        image: "https://dragonball-api.com/characters/zarbon.webp"
                        affiliation: "Army of Frieza"
                        deletedAt: null
                      - id: 7
                        name: "Dodoria"
                        ki: "18.000"
                        maxKi: "20.000"
                        race: "Frieza Race"
                        gender: "Male"
                        description: "Dodoria es otro secuaz de Freezer conocido por su brutalidad."
                        image: "https://dragonball-api.com/characters/dodoria.webp"
                        affiliation: "Army of Frieza"
                        deletedAt: null
                      - id: 8
                        name: "Ginyu"
                        ki: "9.000"
                        maxKi: "25.000"
                        race: "Frieza Race"
                        gender: "Male"
                        description: "Ginyu es el líder del la élite de mercenarios de mayor prestigio del Ejército de Freeza, la cual lleva el nombre de Fuerzas Especiales Ginew en su honor[9]."
                        image: "https://dragonball-api.com/characters/ginyu.webp"
                        affiliation: "Army of Frieza"
                        deletedAt: null
                      - id: 9
                        name: "Celula"
                        ki: "250.000.000"
                        maxKi: "5 Billion"
                        race: "Android"
                        gender: "Male"
                        description: "Cell conocido como Célula en España, es un bioandroide creado por la computadora del Dr. Gero, quien vino del futuro de la línea 3 con la intención de vengarse de Goku por haber acabado con el Ejército del Listón Rojo, y con ello el sueño de todo villano: dominar el mundo. Es el antagonista principal del Arco de los Androides y Cell."
                        image: "https://dragonball-api.com/characters/celula.webp"
                        affiliation: "Freelancer"
                        deletedAt: null
                      - id: 10
                        name: "Gohan"
                        ki: "45.000.000"
                        maxKi: "40 septillion"
                        race: "Saiyan"
                        gender: "Male"
                        description: "Son Gohanda en su tiempo en España, o simplemente Gohan en Hispanoamérica, es uno de los personajes principales de los arcos argumentales de Dragon Ball Z, Dragon Ball Super y Dragon Ball GT. Es un mestizo entre saiyano y humano terrícola. Es el primer hijo de Son Goku y Chi-Chi, hermano mayor de Son Goten, esposo de Videl y padre de Pan."
                        image: "https://dragonball-api.com/characters/gohan.webp"
                        affiliation: "Z Fighter"
                        deletedAt: null
                    meta:
                      totalItems: 58
                      itemCount: 10
                      itemsPerPage: 10
                      totalPages: 6
                      currentPage: 1
                    links:
                      first: "https://dragonball-api.com/api/characters?limit=10"
                      previous: null
                      next: "https://dragonball-api.com/api/characters?page=2&limit=10"
                      last: "https://dragonball-api.com/api/characters?page=6&limit=10"
                filtered:
                  summary: Filtered (?name=vegeta) → array
                  value:
                    - id: 2
                      name: "Vegeta"
                      ki: "54.000.000"
                      maxKi: "19.84 Septillion"
                      race: "Saiyan"
                      gender: "Male"
                      description: "Description..."
                      image: "https://dragonball-api.com/characters/Vegeta.webp"
                      affiliation: "Z Fighter"
                      deletedAt: null
        "400":
          description: "Bad request"
        "404":
          description: "Resource not found"
        "500":
          description: "Internal server error"
  /api/characters/{id}:
    get:
      summary: Get single character with extra parameters by providing an specific id
      tags: [Characters]
      parameters:
        - name: id
          in: path
          required: true
          description: Character id
          schema: { type: number }
      responses:
        "200":
          description: Character Information
          content:
            application/json:
              schema: { $ref: "#/components/schemas/CharacterDetailed" }
              examples:
                CharacterDetailed:
                  value:
                    items:
                    - id: 1
                      name: "Goku"
                      ki: "60.000.000"
                      maxKi: "90 Septillion"
                      race: "Saiyan"
                      gender: "Male"
                      description: "El protagonista de la serie, conocido por su gran poder y personalidad amigable. Originalmente enviado a la Tierra como un infante volador con la misión de conquistarla. Sin embargo, el caer por un barranco le proporcionó un brutal golpe que si bien casi lo mata, este alteró su memoria y anuló todos los instintos violentos de su especie, lo que lo hizo crecer con un corazón puro y bondadoso, pero conservando todos los poderes de su raza. No obstante, en la nueva continuidad de Dragon Ball se establece que él fue enviado por sus padres a la Tierra con el objetivo de sobrevivir a toda costa a la destrucción de su planeta por parte de Freeza. Más tarde, Kakarot, ahora conocido como Son Goku, se convertiría en el príncipe consorte del monte Fry-pan y líder de los Guerreros Z, así como el mayor defensor de la Tierra y del Universo 7, logrando mantenerlos a salvo de la destrucción en innumerables ocasiones, a pesar de no considerarse a sí mismo como un héroe o salvador."
                      image: "https://dragonball-api.com/characters/goku_normal.webp"
                      affiliation: "Z Fighter"
                      deletedAt: null
                      originPlanet:
                        - id: 3
                          name: "Planet Vegeta"
                          isDestroyed: true
                          description: "Planeta natal de la raza Saiyan, destruido por Freezer"
                          image: "https://dragonball-api.com/planets/vegeta.png"
                          deletedAt: null
                      transformations:
                        - id: "1"
                          name: "Super Saiyan"
                          image: "https://dragonball-api.com/transformations/ssj.png"
                          ki: "150.000.000"
                          deletedAt: null
                        - id: "2"
                          name: "Super Saiyan 2"
                          image: "https://dragonball-api.com/transformations/ssj2.png"
                          ki: "300.000.000"
                          deletedAt: null
        "400":
          description: "Bad request"
        "404":
          description: "Resource not found"
        "500":
          description: "Internal server error"
  /api/planets:
    get:
      summary: Get all planets if no params are provided, limit to 10 by default
      tags: [Planets]
      parameters:
        - name: Page
          in: query
          description: Page number
          schema: { type: number }
        - name: Limit
          in: query
          description: Number of items per page
          schema: { type: number }
        - name: Name
          in: query
          description: Character name
          schema: { type: string }
        - name: isDestroyed
          in: query
          description: Wether or not the planet is destroyed
          schema: { type: boolean, nullable: true }
      responses:
        "200":
          description: Planet List
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/PaginatedPlanets"
                  - type: array
                    items:
                      $ref: "#/components/schemas/Planet"
              examples:
                paginated:
                  summary: Unfiltered (paginated)
                  value:
                    items:
                      - id: 1
                        name: "Tierra"
                        isDestroyed: false
                        description: "Planeta natal de Goku y hogar de los guerreros Z"
                        image: "https://dragonball-api.com/planets/tierra.png"
                        deletedAt: null
                    meta:
                      totalItems: 25
                      itemCount: 10
                      itemsPerPage: 10
                      totalPages: 3
                      currentPage: 1
                    links: 
                      first: https://dragonball-api.com/api/planets?limit=10
                      previous: null
                      next: https://dragonball-api.com/api/planets?page=2&limit=10
                      last: https://dragonball-api.com/api/planets?page=2&limit=10
                filtered:
                  summary: Filtered (?name=Namek) → array
                  value:
                    - id: 2
                      name: "Namek"
                      isDestroyed: true
                      description: "Planeta de los Namekianos, destruido por Freezer"
                      image: "https://dragonball-api.com/planets/namek.png"
                      deletedAt: null
        "400":
          description: "Bad request"
        "404":
          description: "Resource not found"
        "500":
          description: "Internal server error"
  /api/planets/{id}:
    get:
      summary: Get single planet with extra parameters by providing an specific id
      tags: [Planets]
      parameters:
        - name: id
          in: path
          required: true
          description: Planet id
          schema: { type: number }
      responses:
        "200":
          description: Planet Information
          content:
            application/json:
              schema: { $ref: "#/components/schemas/PlanetDetailed" }
              examples:
                PlanetDetailed:
                  value:
                    items:
                      - id: 3
                        name: "Planet Vegeta"
                        isDestroyed: true
                        description: "Planeta natal de la raza Saiyan, destruido por Freezer"
                        image: "https://dragonball-api.com/planets/vegeta.png"
                        deletedAt: null
                        characters:
                          - id: 1
                            name: "Goku"
                            ki: "60.000.000"
                            maxKi: "90 Septillion"
                            race: "Saiyan"
                            gender: "Male"
                            description: "El protagonista de la serie, conocido por su gran poder y personalidad amigable. Originalmente enviado a la Tierra como un infante volador con la misión de conquistarla. Sin embargo, el caer por un barranco le proporcionó un brutal golpe que si bien casi lo mata, este alteró su memoria y anuló todos los instintos violentos de su especie, lo que lo hizo crecer con un corazón puro y bondadoso, pero conservando todos los poderes de su raza. No obstante, en la nueva continuidad de Dragon Ball se establece que él fue enviado por sus padres a la Tierra con el objetivo de sobrevivir a toda costa a la destrucción de su planeta por parte de Freeza. Más tarde, Kakarot, ahora conocido como Son Goku, se convertiría en el príncipe consorte del monte Fry-pan y líder de los Guerreros Z, así como el mayor defensor de la Tierra y del Universo 7, logrando mantenerlos a salvo de la destrucción en innumerables ocasiones, a pesar de no considerarse a sí mismo como un héroe o salvador."
                            image: "https://dragonball-api.com/characters/goku_normal.webp"
                            affiliation: "Z Fighter"
                            deletedAt: null
                          - id: 2
                            name: "Vegeta"
                            ki: "54.000.000"
                            maxKi: "19.84 Septillion"
                            race: "Saiyan"
                            gender: "Male"
                            description: "Príncipe de los Saiyans, inicialmente un villano, pero luego se une a los Z Fighters. A pesar de que a inicios de Dragon Ball Z, Vegeta cumple un papel antagónico, poco después decide rebelarse ante el Imperio de Freeza, volviéndose un aliado clave para los Guerreros Z. Con el paso del tiempo llegaría a cambiar su manera de ser, optando por permanecer y vivir en la Tierra para luchar a su lado contra las inminentes adversidades que superar. Junto con Piccolo, él es de los antiguos enemigos de Goku que ha evolucionando al pasar de ser un villano y antihéroe, a finalmente un héroe a lo largo del transcurso de la historia, convirtiéndose así en el deuteragonista de la serie."
                            image: "https://dragonball-api.com/characters/vegeta_normal.webp"
                            affiliation: "Z Fighter"
                            deletedAt: null
        "400":
          description: "Bad request"
        "404":
          description: "Resource not found"
        "500":
          description: "Internal server error"
  /api/tranformations:
    get:
      summary: Get all transformations if no params are provided, limit 10 by default
      tags: [Transformations]
      responses:
        "200":
          description: Transformations List
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/PaginatedTransformations"
                  - type: array
                    items:
                      $ref: "#/components/schemas/Transformation"
              examples:
                paginated:
                  summary: Unfiltered (paginated)
                  value:
                    - id: "1"
                      name: "Super Saiyan"
                      image: "https://dragonball-api.com/transformations/ssj.png"
                      ki: "150.000.000"
                      deletedAt: null
                    - id: "2"
                      name: "Super Saiyan 2"
                      image: "https://dragonball-api.com/transformations/ssj2.png"
                      ki: "300.000.000"
                      deletedAt: null
                filtered:
                  summary: Filtered (?name=Super%20Saiyan) → array
                  value:
                    - id: "1"
                      name: "Super Saiyan"
                      image: "https://dragonball-api.com/transformations/ssj.png"
                      ki: "150.000.000"
                      deletedAt: null
                      characters:
        "400":
          description: "Bad request"
        "404":
          description: "Resource not found"
        "500":
          description: "Internal server error"
  /api/tranformations/{id}:
    get:
      summary: Get all transformations if no params are provided, limit 10 by default
      tags: [Transformations]
      parameters:
        - name: id
          in: path
          required: true
          description: Transformation id
          schema: { type: number }
      responses:
        "200":
          description: Transformation Information
          content:
            application/json:
              schema: { $ref: "#/components/schemas/TransformationDetailed" }
              examples:
                TransformationDetailed:
                  value:
                    items:
                      - id: "1"
                        name: "Super Saiyan"
                        image: "https://dragonball-api.com/transformations/ssj.png"
                        ki: "150.000.000"
                        deletedAt: null
                        characters:
                          - id: 1
                            name: "Goku"
                            ki: "60.000.000"
                            maxKi: "90 Septillion"
                            race: "Saiyan"
                            gender: "Male"
                            description: "El protagonista de la serie, conocido por su gran poder y personalidad amigable. Originalmente enviado a la Tierra como un infante volador con la misión de conquistarla. Sin embargo, el caer por un barranco le proporcionó un brutal golpe que si bien casi lo mata, este alteró su memoria y anuló todos los instintos violentos de su especie, lo que lo hizo crecer con un corazón puro y bondadoso, pero conservando todos los poderes de su raza. No obstante, en la nueva continuidad de Dragon Ball se establece que él fue enviado por sus padres a la Tierra con el objetivo de sobrevivir a toda costa a la destrucción de su planeta por parte de Freeza. Más tarde, Kakarot, ahora conocido como Son Goku, se convertiría en el príncipe consorte del monte Fry-pan y líder de los Guerreros Z, así como el mayor defensor de la Tierra y del Universo 7, logrando mantenerlos a salvo de la destrucción en innumerables ocasiones, a pesar de no considerarse a sí mismo como un héroe o salvador."
                            image: "https://dragonball-api.com/characters/goku_normal.webp"
                            affiliation: "Z Fighter"
                            deletedAt: null
                          - id: 2
                            name: "Vegeta"
                            ki: "54.000.000"
                            maxKi: "19.84 Septillion"
                            race: "Saiyan"
                            gender: "Male"
                            description: "Príncipe de los Saiyans, inicialmente un villano, pero luego se une a los Z Fighters. A pesar de que a inicios de Dragon Ball Z, Vegeta cumple un papel antagónico, poco después decide rebelarse ante el Imperio de Freeza, volviéndose un aliado clave para los Guerreros Z. Con el paso del tiempo llegaría a cambiar su manera de ser, optando por permanecer y vivir en la Tierra para luchar a su lado contra las inminentes adversidades que superar. Junto con Piccolo, él es de los antiguos enemigos de Goku que ha evolucionando al pasar de ser un villano y antihéroe, a finalmente un héroe a lo largo del transcurso de la historia, convirtiéndose así en el deuteragonista de la serie."
                            image: "https://dragonball-api.com/characters/vegeta_normal.webp"
                            affiliation: "Z Fighter"
                            deletedAt: null
        "400":
          description: "Bad request"
        "404":
          description: "Resource not found"
        "500":
          description: "Internal server error"
components:
  schemas:
    Character:
      type: object
      properties:
        id: { type: number, example: 1 }
        name: { type: string, example: "Goku" }
        ki: { type: string, example: "60.000.000" }
        maxKi: { type: string, example: "90 Septillion" }
        race: { type: string, example: Saiyan }
        gender: { type: string, example: Male }
        description: { type: string, example: "Description Goku..." }
        image: 
          type: string
          format: uri
          example: https://dragonball-api.com/characters/goku_normal.webp 
        affiliation: { type: string, example: "Z Fighter" }
        deletedAt: { type: boolean, nullable: true, example: null }
    Planet:
      type: object
      properties:
        id: { type: number, example: 1 }
        name: { type: string, example: "Planet Vegeta" }
        description: { type: string, example: "Description Planet Vegeta..." }
        image:
          type: string
          format: uri
          example: https://dragonball-api.com/planets/planet_vegeta.webp
    Transformation:
      type: object
      properties:
        id: { type: number, example: 1 }
        name: { type: string, example: "Goku SSJ" }
        image:
          type: string
          format: uri
          example: https://dragonball-api.com/transformations/goku_ssj.webp
        ki: { type: number, example: "3 Billion" }
        deletedAt: { type: boolean, nullable: true, example: null }
    PaginationMeta:
      type: object
      properties:
        totalItems: { type: number, example: x }
        itemCount: { type: number, example: 10 }
        itemsPerPage: { type: number, example: 10 }
        totalPages: { type: number, example: x }
        currentPage: { type: number, example: 1 }
    PaginationLinks:
      type: object
      properties:
        first:
          type: string
          nullable: true
          example: "https://dragonball-api.com/api/(characters/planets/transformations)?page=1&limit=10"
        previous:
          type: string
          nullable: true
          example: null
        next: 
          type: string
          nullable: true
          example: "https://dragonball-api.com/api/(characters/planets/transformations)?page=2&limit=10"
        last: 
          type: string
          nullable: true
          example: "https://dragonball-api.com/api/(characters/planets/transformations)?page=x&limit=10" 
    PaginatedCharacters:
      type: object
      properties:
        items:
          type: array
          items: { $ref: "#/components/schemas/Character" }
        meta: { $ref: "#/components/schemas/PaginationMeta" }
        links: { $ref: "#/components/schemas/PaginationLinks" }
    PaginatedPlanets:
      type: object
      properties:
        items:
          type: array
          items: { $ref: "#/components/schemas/Planet" }
        meta: { $ref: "#/components/schemas/PaginationMeta" }
        links: { $ref: "#/components/schemas/PaginationLinks" }
    PaginatedTransformations:
      type: object
      properties:
        items:
          type: array
          items: { $ref: "#/components/schemas/Transformation" }
        meta: { $ref: "#/components/schemas/PaginationMeta" }
        links: { $ref: "#/components/schemas/PaginationLinks" }
    CharacterDetailed:
      allOf:
        - $ref: "#/components/schemas/Character"
        - type: object
          properties:
            originPlanet: { $ref: "#/components/schemas/Planet" }
            transformations: { $ref: "#/components/schemas/Transformation" }
    PlanetDetailed:
      allOf: 
        - $ref: "#/components/schemas/Planet"
        - type: object
          properties:
            characters: { $ref: "#/components/schemas/Character" }
    TransformationDetailed:
      allOf:
        - $ref: "#/components/schemas/Transformation"
        - type: object
          properties:
            characters: { $ref: "#/components/schemas/Character" }